add controllers
tipcat-net/tipcat-net-api pull request #5
Opened 2021-09-02 08:46 UTC by islomN

added controllers (without actions), change gitignore

2021-09-02 19:28 UTC, kirillta requested changes
Waiting for changes

2021-09-03 07:48 UTC, islomN commented
add only test controller action, this action for front check token

2021-09-03 08:46 UTC, kirillta requested changes

2021-09-03 08:46 UTC, kirillta commented on TipCatDotNet.Api/Controllers/CompanyController.cs
> +        [HttpGet("get-all")]
By the way, Get All should be in another controller, so here we need only one Get, which returns only available companies for a token

2021-09-03 08:46 UTC, kirillta commented on TipCatDotNet.Api/Controllers/EmployeeController.cs
> +    [Route("api/employee")]
`api/employees`

2021-09-03 08:46 UTC, kirillta commented on TipCatDotNet.Api/Data/Models/PermissionLevel.cs
> +    public enum PermissionLevel: byte
Why do we need this, if we have [HospitalityFacilityPermissions](https://github.com/tipcat-net/tipcat-net-api/pull/5/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.csproj&file-filters%5B%5D=.json#diff-b6321859ad6051ba014798c822d6e7ba1a083f7e49bf7fbfe668d81765841ab1) already?

2021-09-03 08:46 UTC, kirillta commented on TipCatDotNet.Api/Data/Models/User.cs
> +        [Column("password_hash")]
We nave no data on passwords. Fields may be removed

2021-09-03 08:46 UTC, kirillta commented on TipCatDotNet.Api/Data/Models/User.cs
> +    public class User
Why can't we merge both owners and employees to the one `Employee` table? There aren't much differences

2021-09-03 08:46 UTC, kirillta commented on TipCatDotNet.Api/Data/Models/Owner.cs
> +    public class Owner
Use one term for program classes and database entities. This is much safer and clearer.

2021-09-03 08:46 UTC, kirillta commented on TipCatDotNet.Api/Data/Models/ModelStatus.cs
> +        InActive = 0,
Inactive is one word

2021-09-03 10:48 UTC, kirillta requested changes

2021-09-03 10:48 UTC, kirillta commented on TipCatDotNet.Api/Data/Models/Employee.cs
> +        [ForeignKey("CompanyId")]
Here should be `AccountId`, I presume

2021-09-03 10:48 UTC, kirillta commented on TipCatDotNet.Api/Data/Models/Employee.cs
> +        public virtual User User { get; set; }
Please, move keys to the bottom of the class

2021-09-03 12:24 UTC, kirillta approved these changes

2021-09-03 12:24 UTC, kirillta commented on TipCatDotNet.Api/TipCatDotNet.Api.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
Debug only condition looks like an error

2021-09-03 12:25 UTC, kirillta requested changes
Changes required

2021-09-04 06:18 UTC, evm-andrey approved these changes

2021-09-04 19:41 UTC, kirillta commented
These features merged in another branch

2021-09-04 19:41 UTC, closed without merging